package functionality;

public class Footer extends javax.swing.JPanel {

    /**
     * Creates new form statusBar
     */
    public Footer() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        updateStatus = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        role = new javax.swing.JLabel();
        serverStatus = new javax.swing.JLabel();
        seprator1 = new javax.swing.JSeparator();
        seprator2 = new javax.swing.JSeparator();
        seprator3 = new javax.swing.JSeparator();
        versionControl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 0, 51));
        setPreferredSize(new java.awt.Dimension(1200, 30));

        updateStatus.setForeground(new java.awt.Color(255, 255, 255));

        userName.setForeground(new java.awt.Color(255, 255, 255));

        role.setForeground(new java.awt.Color(255, 255, 255));

        serverStatus.setForeground(new java.awt.Color(255, 255, 255));

        seprator1.setForeground(new java.awt.Color(255, 255, 255));
        seprator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        seprator2.setForeground(new java.awt.Color(255, 255, 255));
        seprator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        seprator3.setForeground(new java.awt.Color(255, 255, 255));
        seprator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        versionControl.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(userName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seprator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(role)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seprator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(serverStatus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seprator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updateStatus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 819, Short.MAX_VALUE)
                                .addComponent(versionControl)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(10, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(updateStatus)
                                                .addComponent(versionControl))
                                        .addComponent(seprator3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(seprator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(userName)
                                                .addComponent(role)
                                                .addComponent(serverStatus)
                                                .addComponent(seprator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
    }// </editor-fold>

    private void init() {
        //userName.setText(Login.userName);
        //role.setText(Login.roleStatus);
        serverStatus.setText(serverCheck ? "Server Running" : "Server Failed");
        updateStatus.setText(updateCheck ? "Up-to-date" : "Lately Updated");
        versionControl.setText("Software Version 1.0");
    }

    private javax.swing.JLabel role;
    private javax.swing.JSeparator seprator1;
    private javax.swing.JSeparator seprator2;
    private javax.swing.JSeparator seprator3;
    private javax.swing.JLabel serverStatus;
    private javax.swing.JLabel updateStatus;
    private javax.swing.JLabel userName;
    private javax.swing.JLabel versionControl;
    // End of variables declaration

    private boolean serverCheck = true;
    private boolean updateCheck = true;
    // End of boolean declaration
}
